### ISSUE TITLE
Multiple issues

### ISSUE THREAD

**Issue by a-support** [ColorlibHQ/Fashe#13]
Hello,

There are a few issues in the Fashe theme that I cannot create a quick fix for:
1. Shopping cart item number does not appear on the upper right on mobile. It does not seem to add anything to the cart on mobile.
2. When the shopping cart icon is clicked on the upper right it pushed the page width out more to the right.
3. The cart page width is too long on mobile so the user has to scroll sideways.

Source:
https://colorlib.com/wp/forums/topic/fashe-shopify-cart-not-appearing-on-mobile/page/2/#post-199043

**Comment by puikinsh** [comment]
@cristianraiber Was these fixed in the last update? 

A lengthy thread is still ongoing on the Colorlib.

**Comment by cristianraiber** [comment]
@puikinsh - did you update the theme on Shopify to the latest version I sent you ? :)

**Comment by cristianraiber** [comment]
@a-support - can you please link the thread on Colorlib that reports these issues so we can take a look?

**Comment by puikinsh** [comment]
The same one as mentioned above: 
https://colorlib.com/wp/forums/topic/fashe-shopify-cart-not-appearing-on-mobile/page/2/#post-199043

Also, got a complaint in the email earlier today.

**Comment by cristianraiber** [comment]
@puikinsh - ok, we'll look into this ASAP

**Comment by puikinsh** [comment]
Some more from emails (haven't tested myself):

1. On mobile, when I tap on a product, add to cart pops up, then I tap on add to cart, and then I have to tap it Again for it to add to cart..

2. When the product is finally added to cart, I tap on the cart icon. Now,  I Cannot tap on the little x icon to remove the item from cart. So I tap on view cart and I still cannot remove my items from the cart, in fact nothing is working to remove the item from cart.

3. The view cart page is not fitted to mobile.

4. The countdown Timer on mobile is a bit messed up.

5. On desktop I can click on the cart icon and click the little x to remove the product. But when I click on view cart there is no way to remove the product in there...

6.Not able to change the colour of the countdown timer on the featured product.

7. Not able to view the product at all unless I clicked on the product title..this is another major problem..It only give the option to add to cart and then view cart..cannot click on the product image to see the item. We should be able to just click on the image to view the product and all variants.

8.Cannot view product variants on mobile and desktop..Another big one.

9. When the promo strip is removed from the top of the banner, it leaves a large white space.

10. There is no way to to centre the footer menu, So on mobile the sub button is of to the right or left somewhere. It need to be optimized for mobil.

**Comment by cristianraiber** [comment]
Yay, more bugs! :D

**Comment by puikinsh** [comment]
Any news on the update for this?
For this theme, I receive far too many complaints via email, FB, Twitter and so on.

**Comment by cristian-e** [comment]
> Shopping cart item number does not appear on the upper right on mobile. It does not seem to add anything to the cart on mobile.

Can't replicate this issue any longer.
![33](https://user-images.githubusercontent.com/43263346/51537136-63174180-1e56-11e9-8d67-6818fce04241.PNG)
<hr>

> When the shopping cart icon is clicked on the upper right it pushed the page width out more to the right.

This issue has been fixed on mobile
![96](https://user-images.githubusercontent.com/43263346/51537376-0a947400-1e57-11e9-906e-43b4ed3c2a93.PNG)

<hr>

> The cart page width is too long on mobile so the user has to scroll sideways.

> The view cart page is not fitted to mobile.

I have changed the css code so that on mobile, the user doesn't have to scroll anymore.
![6](https://user-images.githubusercontent.com/43263346/51537521-7f67ae00-1e57-11e9-8957-22e8b75e950e.PNG)

<hr>

> On mobile, when I tap on a product, add to cart pops up, then I tap on add to cart, and then I have to tap it Again for it to add to cart.

Changes have been made so that the `Add to cart` button is visible by default on mobile.

![956](https://user-images.githubusercontent.com/43263346/51537735-07e64e80-1e58-11e9-8456-560712ae2911.PNG)

<hr>

> When the product is finally added to cart, I tap on the cart icon. Now, I Cannot tap on the little x icon to remove the item from cart. So I tap on view cart and I still cannot remove my items from the cart, in fact nothing is working to remove the item from cart.

> On desktop I can click on the cart icon and click the little x to remove the product. But when I click on view cart there is no way to remove the product in there.

I've added the remove icon to be displayed on mobile as well.

![96](https://user-images.githubusercontent.com/43263346/51537896-7d521f00-1e58-11e9-8d93-b18fc9d4e3e6.PNG).

Also I've added `remove` buttons on the shopping cart table on the `View Cart` page (visible on all devices).

![682](https://user-images.githubusercontent.com/43263346/51538015-c99d5f00-1e58-11e9-974a-3ae6e823804b.PNG)

<hr>

> The countdown Timer on mobile is a bit messed up.

I've decreased the size, on mobile.

![52](https://user-images.githubusercontent.com/43263346/51538104-0a957380-1e59-11e9-8d91-d2e1e0ce152d.PNG)

<hr>

> Not able to change the colour of the countdown timer on the featured product.

I've added settings for changing the background and text color of the countdown timer.

![562](https://user-images.githubusercontent.com/43263346/51538287-90192380-1e59-11e9-8a65-bcef93d23c6c.PNG)

<hr>

> Not able to view the product at all unless I clicked on the product title..this is another major problem..It only give the option to add to cart and then view cart..cannot click on the product image to see the item. We should be able to just click on the image to view the product and all variants.

Clicking on the product image will now direct the user to the single product page.

<hr>

> Cannot view product variants on mobile and desktop. Another big one.

Can't replicate this issue. On mobile I can cycle through the product variants just like on desktop
![66](https://user-images.githubusercontent.com/43263346/51538492-1a618780-1e5a-11e9-8314-b354e776110e.PNG)


<hr>

> When the promo strip is removed from the top of the banner, it leaves a large white space.

Can't replicate this issue with the latest version of the theme.

<hr>

> There is no way to to centre the footer menu, So on mobile the sub button is of to the right or left somewhere. It need to be optimized for mobil.

I've changed the css code so that on mobile, the content from the footer is centered.

![555](https://user-images.githubusercontent.com/43263346/51611852-e608cc80-1f28-11e9-94cd-6e9453e1179f.PNG)
