### ISSUE TITLE
Multible Bugs Mobile and Desktop

### ISSUE THREAD

**Issue by Bmacuser1** [ColorlibHQ/Fashe#20]
Hi guys

since i dont see any open issues here i place them all.

Mobile:
-If you add items it shows the counter in the cart but cart is empty. It looks like the update behavior doesnt work always. Sometimes it shows me 5 items in cart and i click on the cart which gives an empty feedback. Need to reload the site to show them in cart
- Cart icon is on the left instead of the right upper corner
- Search icon is missing on the right buttom corner (That overlays btw the button for going back to the top on the public version of the theme)
- account login icon in header is missing
- not possible to remove items from cart even since the "x" is now existing. Looks like its removed once you reload page but you dont see it visually to get out of the ajax cart view.... 
- Updating cart redirects to checkout which i wouldnt expect here.
Calculation of items in cart in the ajax cart overview is not correct. and even in checkout showing other details here.
- i added 11 of the same items on the product detail page and it adds only quantity 1 or in another case only 2

Desktop: 
- Updating cart redirects to checkout which i wouldnt expect here. It should just remove the item and keep showing me the ajax cart 
- account login icon in header is missing
- Search icon is missing on the right buttom corner (That overlays btw the button for going back to the
- 404 errors on main page if you check with dev console. It tries to load a few images

tested with samsung s7 and chrome 

Video with details
https://share.vidyard.com/watch/dLVpjXmjw3QUxqJnXnQfFM

Let me know if something is unclear. i guess i have to choose another theme base on the topics it has here and not sure if you can fix it immediately 

Cheers Bjoern

**Comment by cristianraiber** [comment]
@cristian-e - please add this to your to-do list; should be implemented after you finish your current tasks

**Comment by cristian-e** [comment]
Submitted changes to the theme that adresses the following issues:

> Cart icon is on the left instead of the right upper corner 

This only happens when you don't have a logo uploaded. I've fixed the positioning so that even when you don't select a logo, the cart icon stays on the right side.

> Search icon is missing on the right buttom corner

I've added a Theme setting (General Settings) that displays a search bar at the bottom of the page, next to the `back to top` button.
![capture](https://user-images.githubusercontent.com/43263346/54033384-db468600-41bc-11e9-94ed-993159cfc716.PNG)
![7](https://user-images.githubusercontent.com/43263346/54033417-f0bbb000-41bc-11e9-966a-ab6f54c68669.PNG)

> account login icon in header is missing

You need to go to `Settings` > `Accounts` > `Customer accounts`, and enable accounts on your shop. The icon will appear in the header.

> Updating cart redirects to checkout which i wouldnt expect here.

When removing an item, or updating item quantity from the cart, you will no longer be redirected to checkout. The cart page will be reloaded with the correct items and quantity. Also, removing an item from the ajax cart overview, will no longer close the dropdown.

> Calculation of items in cart in the ajax cart overview is not correct.

For example when adding three times a product with the price of `5$`, the cart overview was showing `3 x 15$`, which was misleading. It has been fixed to show the correct text: `3 x 5$` .

> i added 11 of the same items on the product detail page and it adds only quantity 1 or in another case only 2

This has also been fixed.

> 404 errors on main page if you check with dev console. It tries to load a few images

Also fixed these errors.

**Comment by Bmacuser1** [comment]
Cool! Do i just need to redownload here latest version?

cristian-e <notifications@github.com> schrieb am Fr., 8. März 2019, 09:48:

**Comment by cristianraiber** [comment]
@Bmacuser1 - yep :)

**Comment by Bmacuser1** [comment]
Hi Cristian

i have tested it again. thanks for the quick update. Did you test the add to cart in detail on mobile or desktop? it still has issues as i mentioned before and i tested mainly for mobile.

# Cart is not shown properly on mobile:

1. add items to cart.
2. its shows the quanitiy in the cart icon but it shows an empty cart

![image](https://user-images.githubusercontent.com/37523944/54100809-5ca14280-438e-11e9-8857-503f90b2ee14.png)

3. once you reload the page the cart is shown properly. i saw that "page reload" issue on several cases. 

# Desktop: If you remove items from cart it closes for each removal the cart ajax. Bug or feature? 

# Remove items from the "/cart" page. It redirects you to checkout which i won't expect here and it doesn't remove the item which is a bug.

https://share.vidyard.com/watch/wh63VBHuK93EuNpbwa9xMr 

The same if you change the quantity and "update" that on the page it redicrects you to the checkout. Is the redirect a feature or bug? other thoughts? 

# Remove items from Mobile:

1. you can click the "x" symbol and it reduces the total number of the cart but it doesnt remove the 

https://share.vidyard.com/watch/GhBv8jpiMt3QEtWJ72u99i

# Move the Menu to the left site on mobile to show the ajax cart properly centered.

I guess if you move the menu hamburger to the left it should show the cart properly centered. 

![image](https://user-images.githubusercontent.com/37523944/54104976-9b8bc400-439f-11e9-9cde-76368c8985c7.png)



Hope it helps :)

Cheers
Björn

**Comment by cristianraiber** [comment]
@cristian-e - see above

**Comment by jasonjophiel** [comment]
Hey there, I am wondering if all these bugs are changed in the latest zip I can download or do I have to follow your mini tutorials on the comments here to fix the bugs, because there are a few, but the biggest one is the items are stuck in the cart, also I would like to add to the bugs.

On mobile, I have to tap the item once to select then tap again to add to cart, I would like it to be just one single tap to add to cart.

Best

**Comment by jasonjophiel** [comment]
> @Bmacuser1 - yep :)

Hello, just wanted to let you know the latest zip file download still has all the issues/bugs an update would be great.

**Comment by cristianraiber** [comment]
We're working on it guys. @cristian-e _is working on it_

**Comment by cristian-e** [comment]
Hello again.
@Bmacuser1 Downloading the latest version should fix all those issues.

I have added some gifs to demonstrate:

> Cart is not shown properly on mobile:
> 1. add items to cart.
> 2. its shows the quanitiy in the cart icon but it shows an empty cart
> 3. once you reload the page the cart is shown properly. i saw that "page reload" issue on several cases.

This issue should be fixed:
![1](https://user-images.githubusercontent.com/43263346/54434437-efe3ca80-4736-11e9-977e-7b284b8f3bb4.gif)

If the issue still persits it might help to know on what page this happens.

<hr>

> Desktop: If you remove items from cart it closes for each removal the cart ajax

This issue should be fixed:
![2](https://user-images.githubusercontent.com/43263346/54434563-3d603780-4737-11e9-842a-277c892b99be.gif)

<hr/>

> Remove items from the "/cart" page. It redirects you to checkout which i won't expect here and it doesn't remove the item which is a bug.

This issue should be fixed as well:
![3](https://user-images.githubusercontent.com/43263346/54434651-6c76a900-4737-11e9-9312-01b512f15f04.gif)

<hr>

> Remove items from Mobile

Again, not an issue anymore (please see first gif). 

<hr>

> Move the Menu to the left site on mobile to show the ajax cart properly centered.

I will include a fix, so that the mobile dropdown will become full width on devices with a maximum screen width of 450px.

![5](https://user-images.githubusercontent.com/43263346/54434940-0f2f2780-4738-11e9-88c2-93ec72b5a01b.gif)

**Comment by Bmacuser1** [comment]
Cool! Thanks Cristian. But code here seems to be still the older version from 7 days ago?

**Comment by hadasabi** [comment]
I also wanted to follow up on the cart issues in the latest version..
