### ISSUE TITLE
Menu problem

### ISSUE THREAD

**Issue by nodarik** [ColorlibHQ/Fashe#4]
> but the menu in the header doesn’t show all categories within the drop down. I have attached a pic to explain better – Under Furniture there are more categories and under Interiors there are other categories, but it’s not displaying in this menu.

https://colorlib.com/wp/forums/topic/fashe-menu-help/

**Comment by SeasideInteriors** [comment]
Hi is there any progress with this?

**Comment by SeasideInteriors** [comment]
I also still have the issue with the skin colour staying red in some places. I have changed it to turquoise, but it only shows turquoise on the "new" products, but everywhere else it is red. (see pic)
2, it still doesn't display when something is sold out... People can still press add to cart but they get this dodgy looking message... (see pic)
3, I just added something to the cart, but it shows my cart is empty, if I try to add it again I get another dodgy looking message (see 2 pics) 
This has been ongoing now for well over a week, (since I first started this theme) and I haven't had any resolutions to these issues as yet. Can something please be done, as right now I'm losing sales as nobody can purchase anything as they can't access the cart.
4, previously in the checkout when I could access it, it had a sentence about shipping being in USD, but I am in Australia and selected AUD, so that wording may need to be edited in the code somewhere. 
Things like the red skin I may be able to do myself if given instructions. I'd really like to have some help with this please as it's getting quite frustrating now. I have been very patient.

**Comment by SeasideInteriors** [comment]
<img width="1252" alt="screen shot 2018-10-03 at 3 53 46 pm" src="https://user-images.githubusercontent.com/43691326/46392758-d8cf9400-c725-11e8-877a-dee77b978b38.png">
<img width="1124" alt="screen shot 2018-10-03 at 3 55 50 pm" src="https://user-images.githubusercontent.com/43691326/46392759-d8cf9400-c725-11e8-87ce-741768ff2348.png">
<img width="756" alt="screen shot 2018-10-03 at 3 58 21 pm" src="https://user-images.githubusercontent.com/43691326/46392762-da00c100-c725-11e8-9eef-3b11cb29c8b8.png">
<img width="999" alt="screen shot 2018-10-03 at 3 59 16 pm" src="https://user-images.githubusercontent.com/43691326/46392763-da00c100-c725-11e8-9aad-d88c84beac29.png">

**Comment by SeasideInteriors** [comment]
*Update - if I refresh the page I can see something in my cart, same if I remove something from the cart, it still shows it in there until I refresh the page. People visiting the site won't refresh, so it needs to work seamlessly if I am to get any sales. Your assistance is appreciated.

**Comment by shahzadmusawwir** [comment]
When using Fashe on Mobile the cart function doesn’t work i.e, When I add a product into the cart and try to click on the Cart Icon. It is unclickable like an image which doesn’t redirects me anywhere. I am very frustrated and many of my customers have raised an issue about this to me.

**Comment by jezripe** [comment]
Hello. I was attempting to implement Fashe as my theme for my shopify store. But there is some issue on the Fashe mobile. The cart function does not work neither does the profile icon. Pls help.

**Comment by jezripe** [comment]
Hi. I found these fixes for the Fashe theme for my website.

For the cart icon that changes as you add items, you will need to adjust in Main CSS.
header-icons-noti
(make sure it's mobile version)
around line: 720

adjust the right: xx%
and top: xx% until you are happy with it.

And for the head icon that's suppose to link to the accounts page,

go to header-1
go to div class="header-icons-mobile"
you want to change the a href="#" to a href="/account" to fix

a href="/account" class="header-wrapicon1 dis-block"
   

And for the box that suppose to pop up when you click your shopping cart
at main.css around line 780
Be sure that it's for mobile.

show-header-dropdown
you want to add the below
    margin-right: 80px;
    margin-top: -45px;

adjust the px until you are happy with the position.

Not sure if you guys can understand what I'm trying to convey.

But it worked for me. Hope it helps you guys too.

:) Peace

**Comment by SeasideInteriors** [comment]
Thanks Jezripe, Do you know if it would be the same for laptop/desktop? My shopping cart shows empty on laptop/desktop after something has been added. The page has to be refreshed for the cart to register anything.

**Comment by jezripe** [comment]
Hey there

I did not actually encounter the same issue on my desktop/laptop.

Glad to hear that whatever worked for me, helped.

Best,
KM

**Comment by SeasideInteriors** [comment]
Thanks Jezripe, your method helped to move the cart number icon over to the shopping bag on mobile, so thank you for that. 

My issue on the desktop is that when something is added to the cart it shows a zero instead of a 1 unless you refresh the page, I'm guessing it's a theme thing? I can't find a fix for that as yet. Thanks for your help! 

I have been able to fix most of the colour issues by editing code in CSS, but there are some areas I can't locate in the CSS like the promotion banner at the very top, the buttons on hover and the top menu on hover, does anyone know where to find these so I can change the colour code please? :)

**Comment by SeasideInteriors** [comment]
Also when I move the icon in mobile it also moves on desktop and I have just noticed that on mobile I can't click the cart icon to go to the cart. Nothing happens...

**Comment by jezripe** [comment]
I have no idea how to fix your problems as I didn't face them.

For the link you might want to make sure it's a href linked to an address.

Sorry cant be of much help.

**Comment by cristianraiber** [comment]
This should be fixed in latest Fashe version.

**Comment by hadasabi** [comment]
> This should be fixed in latest Fashe version.

Hi Christian, any updates about this issue? (*on mobile - cart showing empty unless you refresh the page)

thanks!
