### ISSUE TITLE
Some other issues

### ISSUE THREAD

**Issue by puikinsh** [ColorlibHQ/Fashe#9]
Not sure if relevant but might be worth looking into: https://colorlib.com/wp/forums/topic/cartslider/

**Comment by cristianraiber** [comment]
@giucu91 - we need to look into this as well

**Comment by cristianraiber** [comment]
@cristian-e - it's yours :)

**Comment by cristian-e** [comment]
> On desktop view, the black circle icon shows the number of products in the cart is perfectly placed together with the cart bag icon but on mobile view, its displaced.

This doesn't seem to be an issue any longer 
![33](https://user-images.githubusercontent.com/43263346/51611531-1d2aae00-1f28-11e9-9fc6-7f6d7e08ea63.PNG)

<hr>

> The Instagram feed images are not aligned horizontally currently.

This issue occurs when some images from instagram aren't square. I have fixed this issue with the latest commit.

<hr>

> The cart icon is not clickable on mobile and products show twice on the cart on the desktop too.
> When adding a product to cart is not visible until the page is refresh

These issues have been fixed with the latest commit
